version: "3.7"

services:
  caddy:
    image: abiosoft/caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - spacex
    environment:
      ACME_AGREE: "true"
      CLOUDFLARE_EMAIL: null
      CLOUDFLARE_API_KEY: null
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  api:
    image: jakewmeyer/spacex-api:latest
    ports:
      - "5000:5000"
    networks:
      - spacex
    environment:
      NODE_ENV: production
      DOCKER: "true"
      MONGO_URL: null
      REDIS_URL: null
    depends_on:
      - redis
      - caddy
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - spacex
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

networks:
  spacex:
    driver: overlay
    attachable: true
